"use strict";
let lname = "John";
let newname = lname.toUpperCase();
console.log(newname);
let age;
age = 20;
let dob = "20";
//console.log(age);
//console.log(dob);
let result = parseInt(dob);
//console.log(result);
result += age;
//console.log(result);
let isvalid;
isvalid = true;
//console.log(isvalid);
let emptylist = []; // this is an any datatype
let listb;
listb = ["John", "Doe"];
let listc;
listc = [1, 2, 3, 4, 5];
let results = listc.filter((num) => num > 2);
//console.log(results);
let reduction = listc.reduce((acc, num) => acc + num);
//console.log(reduction);
let user = { name: "John", age: 20, email: "john.doe@email.com" };
let email = user.email;
console.log(email);
console.log(typeof user);
